// Aggregator for the per-topic question catalogs.
// Generated by the catalog splitter. Each topic file owns its own questions
// and any trace helpers specific to that topic.

import type { Question } from "./types";
import { QUESTIONS as arraysQuestions } from "./questions/arrays";
import { QUESTIONS as hashingQuestions } from "./questions/hashing";
import { QUESTIONS as twopointersQuestions } from "./questions/twoPointers";
import { QUESTIONS as linkedlistsQuestions } from "./questions/linkedLists";
import { QUESTIONS as stacksqueuesQuestions } from "./questions/stacksQueues";
import { QUESTIONS as treesQuestions } from "./questions/trees";
import { QUESTIONS as heapsQuestions } from "./questions/heaps";
import { QUESTIONS as graphsQuestions } from "./questions/graphs";
import { QUESTIONS as recursionQuestions } from "./questions/recursion";
import { QUESTIONS as dpQuestions } from "./questions/dp";
import { QUESTIONS as greedyQuestions } from "./questions/greedy";
import { QUESTIONS as binarysearchQuestions } from "./questions/binarySearch";
import { QUESTIONS as sortingQuestions } from "./questions/sorting";
import { QUESTIONS as bitsQuestions } from "./questions/bits";

export const QUESTIONS: Question[] = [
  ...arraysQuestions,
  ...hashingQuestions,
  ...twopointersQuestions,
  ...linkedlistsQuestions,
  ...stacksqueuesQuestions,
  ...treesQuestions,
  ...heapsQuestions,
  ...graphsQuestions,
  ...recursionQuestions,
  ...dpQuestions,
  ...greedyQuestions,
  ...binarysearchQuestions,
  ...sortingQuestions,
  ...bitsQuestions,
];

export const QUESTION_BY_ID: Record<string, Question> = Object.fromEntries(
  QUESTIONS.map((q) => [q.id, q])
);
